// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class PcbsDefaultFirebaseOptions {
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: ' ',
    appId: '1:724372178164:android:77c9d1e6343dbf9f5bcaa1',
    messagingSenderId: '724372178164',
    projectId: 'pace-creative-british-school',
    storageBucket: 'pace-creative-british-school.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA8uKhHR6M1G18y9vuiER78F2_aIinA64',
    appId: '1:724372178164:ios:2b88638b93a3fe665bcaa1',
    messagingSenderId: '724372178164',
    projectId: 'pace-creative-british-school',
    storageBucket: 'pace-creative-british-school.appspot.com',
    iosClientId:
        '724372178164-lrdlqv4h9ol47f6v4n6l9m2nbvd72of2.apps.googleusercontent.com',
    iosBundleId: 'com.pcbs.schoolapp',
  );

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
}
